inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - "db/schema.rb"
    - "bin/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "test/**/*"
